import io
import json
import urllib.request
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, Color
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, Table, TableStyle, HRFlowable, Flowable,
    KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.utils import ImageReader


GREEN_800 = HexColor("#166534")
GREEN_100 = HexColor("#DCFCE7")
GREEN_50 = HexColor("#F0FDF4")
GRAY_900 = HexColor("#111827")
GRAY_700 = HexColor("#374151")
GRAY_600 = HexColor("#4B5563")
GRAY_400 = HexColor("#9CA3AF")
GRAY_200 = HexColor("#E5E7EB")
WHITE = HexColor("#FFFFFF")


# ─── Shared Design Tokens (LaTeX-inspired tight spacing) ───────
SIZE_NAME = 18
SIZE_SECTION = 11
SIZE_BODY = 9.5
SIZE_ENTRY_TITLE = 10
SIZE_SUB = 8.5
SIZE_SMALL = 7.5
SIZE_CONTACT = 8.5

BULLET_CHAR = "\u2022"
CONTACT_SEP = " \u00a0|\u00a0 "

SPACE_SECTION_BEFORE = 3.5 * mm
SPACE_SECTION_AFTER = 1.5 * mm
SPACE_ENTRY_GAP = 1.2 * mm

MARGIN_STANDARD = 10 * mm   # Was 18mm — now tight like LaTeX resumes
MARGIN_TIGHT = 8 * mm       # Was 15mm


def _leading(font_size: float, multiplier: float = 1.4) -> float:
    return round(font_size * multiplier, 1)


def _add_footer(elements: list, styles):
    """Minimal branding footer (~3mm total) — added to element list as fallback."""
    elements.append(Spacer(1, 4 * mm))
    elements.append(HRFlowable(width="40%", thickness=0.3, color=GRAY_200, spaceAfter=1.5 * mm))
    s = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=6.5, textColor=GRAY_400, alignment=TA_CENTER)
    elements.append(Paragraph("Generated by iKlavya  \u00b7  iklavya.in", s))


def _draw_page_footer(canvas, doc):
    """Draw footer at the bottom of every page — ensures it's always at page bottom."""
    canvas.saveState()
    width = doc.pagesize[0]
    # Draw thin line
    canvas.setStrokeColor(GRAY_200)
    canvas.setLineWidth(0.3)
    canvas.line(width * 0.3, 10 * mm, width * 0.7, 10 * mm)
    # Draw text
    canvas.setFont("Helvetica", 6.5)
    canvas.setFillColor(GRAY_400)
    canvas.drawCentredString(width / 2, 7 * mm, "Generated by iKlavya  \u00b7  iklavya.in")
    canvas.restoreState()


def _build_entry_row(left_text: str, right_text: str, s_left, s_right, total_width: float):
    """Two-column row: title on left, date/info on right."""
    t = Table(
        [[Paragraph(left_text, s_left), Paragraph(right_text, s_right)]],
        colWidths=[total_width * 0.72, total_width * 0.28],
    )
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
    ]))
    return t


def generate_resume_pdf(
    resume_json,
    template: str = "professional",
    profile_image_url: str | None = None,
) -> bytes:
    """Generate resume PDF bytes for the given template."""
    # Handle both str (from DB) and dict (already parsed) inputs
    if isinstance(resume_json, dict):
        data = resume_json
    else:
        data = json.loads(resume_json)
    if template == "modern":
        return _generate_modern(data)
    elif template == "simple":
        return _generate_simple(data)
    elif template == "rendercv":
        return _generate_rendercv(data)
    elif template == "sidebar":
        return _generate_sidebar(data, profile_image_url)
    elif template == "jake":
        return _generate_jake(data)
    return _generate_professional(data)


# ─── Template 1: Professional ───────────────────────────────


def _generate_professional(data: dict) -> bytes:
    """Professional template — LaTeX-inspired tight layout with gray section headers."""
    GRAY_BG = HexColor("#F0F0F0")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=MARGIN_TIGHT, bottomMargin=MARGIN_TIGHT,
        leftMargin=MARGIN_STANDARD, rightMargin=MARGIN_STANDARD,
    )
    content_w = A4[0] - 2 * MARGIN_STANDARD
    styles = getSampleStyleSheet()

    # Styles — tighter leading (1.3x) for dense packing
    s_name = ParagraphStyle("PName", parent=styles["Title"], fontSize=SIZE_NAME, textColor=GRAY_900, spaceAfter=0, alignment=TA_LEFT, fontName="Helvetica-Bold")
    s_contact = ParagraphStyle("PContact", parent=styles["Normal"], fontSize=SIZE_CONTACT, textColor=GRAY_600, spaceAfter=0, alignment=TA_RIGHT)
    s_section = ParagraphStyle("PSection", parent=styles["Normal"], fontSize=SIZE_SECTION, textColor=GRAY_900, fontName="Helvetica-Bold", spaceBefore=SPACE_SECTION_BEFORE, spaceAfter=0, leading=_leading(SIZE_SECTION, 1.2))
    s_body = ParagraphStyle("PBody", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=GRAY_700, leading=_leading(SIZE_BODY, 1.3))
    s_bullet = ParagraphStyle("PBullet", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=GRAY_700, leading=_leading(SIZE_BODY, 1.3), leftIndent=12, bulletIndent=3, spaceBefore=0.3 * mm)
    s_entry_title = ParagraphStyle("PEntryTitle", parent=styles["Normal"], fontSize=SIZE_ENTRY_TITLE, textColor=GRAY_900, leading=_leading(SIZE_ENTRY_TITLE, 1.3), fontName="Helvetica-Bold")
    s_entry_sub = ParagraphStyle("PEntrySub", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=GRAY_600, leading=_leading(SIZE_SUB, 1.3))
    s_entry_right = ParagraphStyle("PEntryRight", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=GRAY_600, leading=_leading(SIZE_SUB, 1.3), alignment=TA_RIGHT)
    s_skill_inline = ParagraphStyle("PSkillInline", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=GRAY_700, leading=_leading(SIZE_BODY, 1.3), spaceBefore=0.5 * mm)

    elements = []
    pi = data.get("personal_info", {})

    # ── Header: Name left, Contact right (2-column table) ──
    name_text = pi.get("name", "Your Name")
    contact_parts = [p for p in [pi.get("email"), pi.get("phone"), pi.get("location")] if p]
    link_parts = [p for p in [pi.get("linkedin"), pi.get("github"), pi.get("portfolio")] if p]
    contact_right = "<br/>".join([CONTACT_SEP.join(contact_parts)] + ([CONTACT_SEP.join(link_parts)] if link_parts else []))

    header = Table(
        [[Paragraph(name_text, s_name), Paragraph(contact_right, s_contact)]],
        colWidths=[content_w * 0.55, content_w * 0.45],
    )
    header.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    elements.append(header)
    elements.append(HRFlowable(width="100%", thickness=1.5, color=GRAY_900, spaceAfter=2 * mm, spaceBefore=1.5 * mm))

    # ── Helper: Section heading with gray background ──
    def add_section(title):
        s_hdr = ParagraphStyle("SHdr", parent=styles["Normal"], fontSize=SIZE_SECTION, textColor=GRAY_900, fontName="Helvetica-Bold", leading=_leading(SIZE_SECTION, 1.2))
        t = Table([[Paragraph(title, s_hdr)]], colWidths=[content_w])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), GRAY_BG),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 2.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
        ]))
        elements.append(Spacer(1, SPACE_SECTION_BEFORE))
        elements.append(t)
        elements.append(Spacer(1, SPACE_SECTION_AFTER))

    # ── Helper: Entry row (title left, date right) ──
    def add_entry_row(left, right):
        t = Table(
            [[Paragraph(left, s_entry_title), Paragraph(right, s_entry_right)]],
            colWidths=[content_w * 0.72, content_w * 0.28],
        )
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))
        elements.append(t)

    # ── Objective ──
    obj = data.get("objective", "")
    if obj:
        add_section("CAREER OBJECTIVE")
        elements.append(Paragraph(obj, s_body))

    # ── Education — bordered table (like GGSIPU template) ──
    edu_list = data.get("education", [])
    if edu_list:
        add_section("EDUCATION")
        edu_header = [
            Paragraph("<b>Year</b>", ParagraphStyle("EH", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=WHITE, fontName="Helvetica-Bold", leading=_leading(SIZE_SUB, 1.2))),
            Paragraph("<b>Degree / Certificate</b>", ParagraphStyle("EH2", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=WHITE, fontName="Helvetica-Bold", leading=_leading(SIZE_SUB, 1.2))),
            Paragraph("<b>Institute</b>", ParagraphStyle("EH3", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=WHITE, fontName="Helvetica-Bold", leading=_leading(SIZE_SUB, 1.2))),
            Paragraph("<b>CGPA / %</b>", ParagraphStyle("EH4", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=WHITE, fontName="Helvetica-Bold", leading=_leading(SIZE_SUB, 1.2))),
        ]
        edu_rows = [edu_header]
        s_edu_cell = ParagraphStyle("ECell", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=GRAY_700, leading=_leading(SIZE_SUB, 1.3))
        for e in edu_list:
            edu_rows.append([
                Paragraph(e.get("year", ""), s_edu_cell),
                Paragraph(f"{e.get('degree', '')}" + (f" ({e['stream']})" if e.get('stream') else ""), s_edu_cell),
                Paragraph(e.get("institution", ""), s_edu_cell),
                Paragraph(e.get("grade", ""), s_edu_cell),
            ])
        edu_t = Table(edu_rows, colWidths=[content_w * 0.15, content_w * 0.35, content_w * 0.35, content_w * 0.15])
        edu_t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), GREEN_800),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("GRID", (0, 0), (-1, -1), 0.5, GRAY_400),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, HexColor("#FAFAFA")]),
        ]))
        elements.append(edu_t)

    # ── Experience ──
    exp_list = data.get("experience", [])
    if exp_list:
        add_section("EXPERIENCE")
        for exp in exp_list:
            title = f"<b>{exp.get('title', '')}</b>"
            if exp.get("company"):
                title += f" | {exp['company']}"
            add_entry_row(title, exp.get("duration", ""))
            if exp.get("location"):
                elements.append(Paragraph(exp["location"], s_entry_sub))
            for b in exp.get("bullets", []):
                elements.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            elements.append(Spacer(1, SPACE_ENTRY_GAP))

    # ── Projects ──
    proj_list = data.get("projects", [])
    if proj_list:
        add_section("PROJECTS")
        for p in proj_list:
            line = f"<b>{p.get('name', '')}</b>"
            ts = p.get("tech_stack", [])
            if ts:
                ts_str = ", ".join(ts) if isinstance(ts, list) else str(ts)
                line += f"  <font color='#6B7280'>({ts_str})</font>"
            elements.append(Paragraph(line, s_entry_title))
            if p.get("description"):
                elements.append(Paragraph(p["description"], s_entry_sub))
            for b in p.get("bullets", []):
                elements.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            elements.append(Spacer(1, SPACE_ENTRY_GAP))

    # ── Skills — inline format (no table, wraps naturally) ──
    skills = data.get("skills", {})
    if any(skills.get(k) for k in ["technical", "soft", "languages", "tools"]):
        add_section("TECHNICAL SKILLS")
        for label, key in [("Languages / Technologies", "technical"), ("Developer Tools", "tools"), ("Soft Skills", "soft"), ("Languages", "languages")]:
            items = skills.get(key, [])
            if items:
                elements.append(Paragraph(f"<b>{label}:</b> {', '.join(items)}", s_skill_inline))

    # ── Achievements ──
    achievements = data.get("achievements", [])
    if achievements:
        add_section("ACHIEVEMENTS")
        for a in achievements:
            elements.append(Paragraph(a, s_bullet, bulletText=BULLET_CHAR))

    # ── Certifications ──
    certs = data.get("certifications", [])
    if certs:
        add_section("CERTIFICATIONS")
        for c in certs:
            line = f"<b>{c.get('name', '')}</b>"
            parts = [p for p in [c.get("issuer"), c.get("year")] if p]
            if parts:
                line += f" — {', '.join(parts)}"
            elements.append(Paragraph(line, s_body))

    doc.build(elements, onFirstPage=_draw_page_footer, onLaterPages=_draw_page_footer)
    buffer.seek(0)
    return buffer.read()


# ─── Template 2: Modern (Two-Column) ────────────────────────


def _generate_modern(data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=MARGIN_TIGHT, bottomMargin=MARGIN_TIGHT,
        leftMargin=MARGIN_TIGHT, rightMargin=MARGIN_TIGHT,
    )
    styles = getSampleStyleSheet()
    page_w = A4[0] - 2 * MARGIN_TIGHT

    # Left column styles (white text on dark bg)
    s_lname = ParagraphStyle("MNameL", parent=styles["Title"], fontSize=16, textColor=WHITE, spaceAfter=2 * mm, alignment=TA_LEFT)
    s_lcontact = ParagraphStyle("MContactL", parent=styles["Normal"], fontSize=8.5, textColor=HexColor("#BBFFBB"), leading=_leading(8.5))
    s_lsection = ParagraphStyle("MSectionL", parent=styles["Heading3"], fontSize=10, textColor=WHITE, spaceBefore=4 * mm, spaceAfter=1.5 * mm)
    s_lbody = ParagraphStyle("MBodyL", parent=styles["Normal"], fontSize=9, textColor=HexColor("#E0E0E0"), leading=_leading(9))
    s_lbullet = ParagraphStyle("MBulletL", parent=styles["Normal"], fontSize=8.5, textColor=HexColor("#E0E0E0"), leading=_leading(8.5), leftIndent=8, bulletIndent=0)

    # Right column styles
    s_rsection = ParagraphStyle("MSectionR", parent=styles["Heading2"], fontSize=SIZE_SECTION, textColor=GREEN_800, spaceBefore=4 * mm, spaceAfter=1 * mm, keepWithNext=1)
    s_rbody = ParagraphStyle("MBodyR", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=GRAY_700, leading=_leading(SIZE_BODY))
    s_rbullet = ParagraphStyle("MBulletR", parent=styles["Normal"], fontSize=9.5, textColor=GRAY_700, leading=_leading(9.5), leftIndent=12, bulletIndent=2)
    s_rtitle = ParagraphStyle("MTitleR", parent=styles["Normal"], fontSize=SIZE_ENTRY_TITLE, textColor=GRAY_900, leading=_leading(SIZE_ENTRY_TITLE))
    s_rsub = ParagraphStyle("MSubR", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=GRAY_400, leading=_leading(SIZE_SUB))

    pi = data.get("personal_info", {})
    skills = data.get("skills", {})

    # Build left column content
    left_elements = []
    left_elements.append(Paragraph(pi.get("name", ""), s_lname))
    for field in ["email", "phone", "location", "linkedin", "portfolio"]:
        val = pi.get(field)
        if val:
            left_elements.append(Paragraph(val, s_lcontact))

    # Skills in left column — bulleted for better readability
    if skills.get("technical"):
        left_elements.append(Paragraph("SKILLS", s_lsection))
        for sk in skills["technical"]:
            left_elements.append(Paragraph(sk, s_lbullet, bulletText=BULLET_CHAR))
    if skills.get("tools"):
        left_elements.append(Paragraph("TOOLS", s_lsection))
        for sk in skills["tools"]:
            left_elements.append(Paragraph(sk, s_lbullet, bulletText=BULLET_CHAR))
    if skills.get("languages"):
        left_elements.append(Paragraph("LANGUAGES", s_lsection))
        left_elements.append(Paragraph(", ".join(skills["languages"]), s_lbody))
    if skills.get("soft"):
        left_elements.append(Paragraph("SOFT SKILLS", s_lsection))
        left_elements.append(Paragraph(", ".join(skills["soft"]), s_lbody))

    certs = data.get("certifications", [])
    if certs:
        left_elements.append(Paragraph("CERTIFICATIONS", s_lsection))
        for c in certs:
            left_elements.append(Paragraph(f"{BULLET_CHAR} {c.get('name', '')} ({c.get('year', '')})", s_lbody))

    # Build right column content
    right_elements = []

    obj = data.get("objective", "")
    if obj:
        right_elements.append(Paragraph("OBJECTIVE", s_rsection))
        right_elements.append(HRFlowable(width="100%", thickness=0.5, color=GREEN_800, spaceAfter=SPACE_SECTION_AFTER))
        right_elements.append(Paragraph(f"<i>{obj}</i>", s_rbody))

    edu_list = data.get("education", [])
    if edu_list:
        right_elements.append(Paragraph("EDUCATION", s_rsection))
        right_elements.append(HRFlowable(width="100%", thickness=0.5, color=GREEN_800, spaceAfter=SPACE_SECTION_AFTER))
        for e in edu_list:
            right_elements.append(Paragraph(f"<b>{e.get('degree', '')}</b> — {e.get('institution', '')}", s_rtitle))
            sub = [p for p in [e.get("year"), e.get("grade")] if p]
            if sub:
                right_elements.append(Paragraph(" | ".join(sub), s_rsub))
            right_elements.append(Spacer(1, SPACE_ENTRY_GAP))

    exp_list = data.get("experience", [])
    if exp_list:
        right_elements.append(Paragraph("EXPERIENCE", s_rsection))
        right_elements.append(HRFlowable(width="100%", thickness=0.5, color=GREEN_800, spaceAfter=SPACE_SECTION_AFTER))
        for exp in exp_list:
            right_elements.append(Paragraph(f"<b>{exp.get('title', '')}</b> — {exp.get('company', '')}", s_rtitle))
            if exp.get("duration"):
                right_elements.append(Paragraph(exp["duration"], s_rsub))
            for b in exp.get("bullets", []):
                right_elements.append(Paragraph(b, s_rbullet, bulletText=BULLET_CHAR))
            right_elements.append(Spacer(1, SPACE_ENTRY_GAP))

    proj_list = data.get("projects", [])
    if proj_list:
        right_elements.append(Paragraph("PROJECTS", s_rsection))
        right_elements.append(HRFlowable(width="100%", thickness=0.5, color=GREEN_800, spaceAfter=SPACE_SECTION_AFTER))
        for p in proj_list:
            tech = f" ({', '.join(p.get('tech_stack', []))})" if p.get("tech_stack") else ""
            right_elements.append(Paragraph(f"<b>{p.get('name', '')}</b>{tech}", s_rtitle))
            for b in p.get("bullets", []):
                right_elements.append(Paragraph(b, s_rbullet, bulletText=BULLET_CHAR))
            right_elements.append(Spacer(1, SPACE_ENTRY_GAP))

    achievements = data.get("achievements", [])
    if achievements:
        right_elements.append(Paragraph("ACHIEVEMENTS", s_rsection))
        right_elements.append(HRFlowable(width="100%", thickness=0.5, color=GREEN_800, spaceAfter=SPACE_SECTION_AFTER))
        for a in achievements:
            right_elements.append(Paragraph(a, s_rbullet, bulletText=BULLET_CHAR))

    # Combine into two-column table
    left_w = page_w * 0.30
    right_w = page_w * 0.70

    left_cell = left_elements if left_elements else [Paragraph("", s_lbody)]
    right_cell = right_elements if right_elements else [Paragraph("", s_rbody)]

    t = Table([[left_cell, right_cell]], colWidths=[left_w, right_w])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), GREEN_800),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("LEFTPADDING", (0, 0), (0, 0), 14),
        ("RIGHTPADDING", (0, 0), (0, 0), 12),
        ("LEFTPADDING", (1, 0), (1, 0), 14),
        ("RIGHTPADDING", (1, 0), (1, 0), 8),
    ]))

    elements = [t]
    doc.build(elements, onFirstPage=_draw_page_footer, onLaterPages=_draw_page_footer)
    buffer.seek(0)
    return buffer.read()


# ─── Template 3: Simple (ATS-Optimized) ─────────────────────


def _generate_simple(data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=MARGIN_STANDARD, bottomMargin=MARGIN_STANDARD,
        leftMargin=MARGIN_STANDARD, rightMargin=MARGIN_STANDARD,
    )
    styles = getSampleStyleSheet()

    s_name = ParagraphStyle("SName", parent=styles["Title"], fontSize=SIZE_NAME, textColor=GRAY_900, spaceAfter=1 * mm, alignment=TA_CENTER)
    s_contact = ParagraphStyle("SContact", parent=styles["Normal"], fontSize=SIZE_CONTACT, textColor=GRAY_600, alignment=TA_CENTER, spaceAfter=4 * mm)
    s_section = ParagraphStyle("SSection", parent=styles["Heading2"], fontSize=SIZE_SECTION, textColor=GRAY_900, spaceBefore=SPACE_SECTION_BEFORE, spaceAfter=1 * mm, keepWithNext=1)
    s_body = ParagraphStyle("SBody", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=GRAY_700, leading=_leading(SIZE_BODY))
    s_bullet = ParagraphStyle("SBullet", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=GRAY_700, leading=_leading(SIZE_BODY), leftIndent=14, bulletIndent=4)
    s_entry = ParagraphStyle("SEntry", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=GRAY_900, leading=_leading(SIZE_BODY))
    s_sub = ParagraphStyle("SSub", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=GRAY_600, leading=_leading(SIZE_SUB))

    elements = []
    pi = data.get("personal_info", {})

    # Header — centered, clean
    elements.append(Paragraph(pi.get("name", ""), s_name))
    contact_parts = [p for p in [pi.get("email"), pi.get("phone"), pi.get("location")] if p]
    if pi.get("linkedin"):
        contact_parts.append(pi["linkedin"])
    elements.append(Paragraph(CONTACT_SEP.join(contact_parts), s_contact))

    # Objective
    obj = data.get("objective", "")
    if obj:
        elements.append(Paragraph("CAREER OBJECTIVE", s_section))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_200, spaceAfter=SPACE_SECTION_AFTER))
        elements.append(Paragraph(obj, s_body))

    # Education
    edu_list = data.get("education", [])
    if edu_list:
        elements.append(Paragraph("EDUCATION", s_section))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_200, spaceAfter=SPACE_SECTION_AFTER))
        for e in edu_list:
            entry = []
            entry.append(Paragraph(f"<b>{e.get('degree', '')}</b> — {e.get('institution', '')}", s_entry))
            sub = [p for p in [e.get("year"), e.get("grade"), e.get("board")] if p]
            if sub:
                entry.append(Paragraph(" | ".join(sub), s_sub))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # Experience
    exp_list = data.get("experience", [])
    if exp_list:
        elements.append(Paragraph("EXPERIENCE", s_section))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_200, spaceAfter=SPACE_SECTION_AFTER))
        for exp in exp_list:
            entry = []
            entry.append(Paragraph(f"<b>{exp.get('title', '')}</b> — {exp.get('company', '')} ({exp.get('duration', '')})", s_entry))
            for b in exp.get("bullets", []):
                entry.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # Projects
    proj_list = data.get("projects", [])
    if proj_list:
        elements.append(Paragraph("PROJECTS", s_section))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_200, spaceAfter=SPACE_SECTION_AFTER))
        for p in proj_list:
            entry = []
            tech = f" [{', '.join(p.get('tech_stack', []))}]" if p.get("tech_stack") else ""
            entry.append(Paragraph(f"<b>{p.get('name', '')}</b>{tech}", s_entry))
            if p.get("description"):
                entry.append(Paragraph(p["description"], s_sub))
            for b in p.get("bullets", []):
                entry.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # Skills — categorized for clarity while staying ATS-friendly
    skills = data.get("skills", {})
    if any(skills.get(k) for k in ["technical", "soft", "languages", "tools"]):
        elements.append(Paragraph("SKILLS", s_section))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_200, spaceAfter=SPACE_SECTION_AFTER))
        if skills.get("technical"):
            elements.append(Paragraph(f"<b>Technical:</b> {', '.join(skills['technical'])}", s_body))
        if skills.get("tools"):
            elements.append(Paragraph(f"<b>Tools:</b> {', '.join(skills['tools'])}", s_body))
        if skills.get("soft"):
            elements.append(Paragraph(f"<b>Soft Skills:</b> {', '.join(skills['soft'])}", s_body))
        if skills.get("languages"):
            elements.append(Paragraph(f"<b>Languages:</b> {', '.join(skills['languages'])}", s_body))

    # Achievements
    achievements = data.get("achievements", [])
    if achievements:
        elements.append(Paragraph("ACHIEVEMENTS", s_section))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_200, spaceAfter=SPACE_SECTION_AFTER))
        for a in achievements:
            elements.append(Paragraph(a, s_bullet, bulletText=BULLET_CHAR))

    # Certifications
    certs = data.get("certifications", [])
    if certs:
        elements.append(Paragraph("CERTIFICATIONS", s_section))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_200, spaceAfter=SPACE_SECTION_AFTER))
        for c in certs:
            elements.append(Paragraph(f"{c.get('name', '')} — {c.get('issuer', '')} ({c.get('year', '')})", s_body))

    doc.build(elements, onFirstPage=_draw_page_footer, onLaterPages=_draw_page_footer)
    buffer.seek(0)
    return buffer.read()


# ─── Template 4: RenderCV Professional (Blue Accent) ─────────

RENDERCV_BLUE = Color(0 / 255, 79 / 255, 144 / 255)
RENDERCV_DARK = HexColor("#222222")
RENDERCV_GRAY = HexColor("#555555")
RENDERCV_LIGHT = HexColor("#888888")


def _generate_rendercv(data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=MARGIN_TIGHT, bottomMargin=MARGIN_TIGHT,
        leftMargin=MARGIN_TIGHT, rightMargin=MARGIN_TIGHT,
    )
    styles = getSampleStyleSheet()
    page_w = A4[0] - 2 * MARGIN_TIGHT

    s_name = ParagraphStyle("RCVName", parent=styles["Title"], fontSize=SIZE_NAME, textColor=RENDERCV_DARK, spaceAfter=2 * mm, alignment=TA_CENTER, fontName="Helvetica-Bold")
    s_contact = ParagraphStyle("RCVContact", parent=styles["Normal"], fontSize=SIZE_CONTACT, textColor=RENDERCV_BLUE, spaceAfter=3 * mm, alignment=TA_CENTER, leading=_leading(SIZE_CONTACT))
    s_section = ParagraphStyle("RCVSection", parent=styles["Heading2"], fontSize=SIZE_SECTION, textColor=RENDERCV_BLUE, spaceBefore=SPACE_SECTION_BEFORE, spaceAfter=1 * mm, fontName="Helvetica-Bold", keepWithNext=1)
    s_entry_l = ParagraphStyle("RCVEntryL", parent=styles["Normal"], fontSize=SIZE_ENTRY_TITLE, textColor=RENDERCV_DARK, leading=_leading(SIZE_ENTRY_TITLE), fontName="Helvetica-Bold")
    s_entry_r = ParagraphStyle("RCVEntryR", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=RENDERCV_GRAY, leading=_leading(SIZE_SUB), alignment=TA_RIGHT)
    s_sub = ParagraphStyle("RCVSub", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=RENDERCV_GRAY, leading=_leading(SIZE_SUB))
    s_bullet = ParagraphStyle("RCVBullet", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=RENDERCV_GRAY, leading=_leading(SIZE_BODY), leftIndent=14, bulletIndent=4)
    s_skills = ParagraphStyle("RCVSkills", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=RENDERCV_DARK, leading=_leading(SIZE_BODY))

    elements = []
    pi = data.get("personal_info", {})

    # Name
    elements.append(Paragraph(pi.get("name", ""), s_name))

    # Contact line
    contact_items = []
    if pi.get("location"):
        contact_items.append(pi["location"])
    if pi.get("email"):
        contact_items.append(pi["email"])
    if pi.get("phone"):
        contact_items.append(pi["phone"])
    if pi.get("portfolio"):
        contact_items.append(pi["portfolio"])
    if pi.get("linkedin"):
        contact_items.append(pi["linkedin"])
    if contact_items:
        elements.append(Paragraph(CONTACT_SEP.join(contact_items), s_contact))

    def add_section(title):
        elements.append(Paragraph(title, s_section))
        elements.append(HRFlowable(width="100%", thickness=0.75, color=RENDERCV_BLUE, spaceAfter=SPACE_SECTION_AFTER))

    # Education
    edu_list = data.get("education", [])
    if edu_list:
        add_section("Education")
        for e in edu_list:
            entry = []
            entry.append(_build_entry_row(
                f"<b>{e.get('institution', '')}</b>", e.get("year", ""),
                s_entry_l, s_entry_r, page_w,
            ))
            degree_line = e.get("degree", "")
            if e.get("grade"):
                degree_line += f" | {e['grade']}"
            if degree_line:
                entry.append(Paragraph(degree_line, s_sub))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # Experience
    exp_list = data.get("experience", [])
    if exp_list:
        add_section("Experience")
        for exp in exp_list:
            entry = []
            left = f"<b>{exp.get('title', '')}</b>"
            if exp.get("company"):
                left += f", <i>{exp['company']}</i>"
            entry.append(_build_entry_row(left, exp.get("duration", ""), s_entry_l, s_entry_r, page_w))
            for b in exp.get("bullets", []):
                entry.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # Projects
    proj_list = data.get("projects", [])
    if proj_list:
        add_section("Projects")
        for p in proj_list:
            entry = []
            title = f"<b>{p.get('name', '')}</b>"
            ts = p.get("tech_stack", [])
            if ts:
                title += f"  <font color='#888888'>({', '.join(ts)})</font>"
            entry.append(Paragraph(title, s_entry_l))
            if p.get("description"):
                entry.append(Paragraph(p["description"], s_sub))
            for b in p.get("bullets", []):
                entry.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # Skills
    skills = data.get("skills", {})
    if any(skills.get(k) for k in ["technical", "soft", "languages", "tools"]):
        add_section("Skills")
        for cat, key in [("Technical Skills", "technical"), ("Languages", "languages"), ("Tools & Frameworks", "tools"), ("Soft Skills", "soft")]:
            if skills.get(key):
                elements.append(Paragraph(f"<b>{cat}:</b> {', '.join(skills[key])}", s_skills))
                elements.append(Spacer(1, 1 * mm))

    # Achievements
    achievements = data.get("achievements", [])
    if achievements:
        add_section("Achievements")
        for a in achievements:
            elements.append(Paragraph(a, s_bullet, bulletText=BULLET_CHAR))

    # Certifications
    certs = data.get("certifications", [])
    if certs:
        add_section("Certifications")
        for c in certs:
            line = f"<b>{c.get('name', '')}</b>"
            parts = [p for p in [c.get("issuer"), c.get("year")] if p]
            if parts:
                line += f" -- {', '.join(parts)}"
            elements.append(Paragraph(line, s_skills))

    doc.build(elements, onFirstPage=_draw_page_footer, onLaterPages=_draw_page_footer)
    buffer.seek(0)
    return buffer.read()


# ─── Template 5: Clean CV Sidebar (Two-Column with Photo) ────

SIDEBAR_TEAL = Color(0 / 255, 112 / 255, 101 / 255)
SIDEBAR_CREAM = Color(245 / 255, 243 / 255, 233 / 255)
SIDEBAR_WHITE = Color(1, 1, 1)
SIDEBAR_DARK = HexColor("#2D2D2D")
SIDEBAR_LIGHT = Color(0.9, 0.9, 0.9)
SIDEBAR_DIM = Color(0.7, 0.7, 0.7)


class CircularImage(Flowable):
    """Renders an image clipped to a circle."""

    def __init__(self, img_data: io.BytesIO, size: float):
        Flowable.__init__(self)
        self.img_data = img_data
        self.size = size
        self.width = size
        self.height = size

    def draw(self):
        r = self.size / 2
        path = self.canv.beginPath()
        path.circle(r, r, r)
        self.canv.clipPath(path, stroke=0)
        self.canv.drawImage(
            ImageReader(self.img_data),
            0, 0, self.size, self.size,
            preserveAspectRatio=True, mask="auto",
        )


def _fetch_image_bytes(url: str) -> io.BytesIO | None:
    """Download image from URL into BytesIO."""
    if not url:
        return None
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            return io.BytesIO(resp.read())
    except Exception:
        return None


def _draw_sidebar_bg(canvas, doc):
    """Paint the two-column background on every page."""
    w, h = A4
    sw = w * 0.38
    canvas.setFillColor(SIDEBAR_TEAL)
    canvas.rect(0, 0, sw, h, fill=1, stroke=0)
    canvas.setFillColor(SIDEBAR_CREAM)
    canvas.rect(sw, 0, w - sw, h, fill=1, stroke=0)


def _generate_sidebar(data: dict, profile_image_url: str | None = None) -> bytes:
    buffer = io.BytesIO()
    w, h = A4
    sw = w * 0.38
    mw = w * 0.62

    doc = BaseDocTemplate(
        buffer, pagesize=A4,
        topMargin=0, bottomMargin=0,
        leftMargin=0, rightMargin=0,
    )
    full_frame = Frame(0, 0, w, h, id="full", leftPadding=0, rightPadding=0, topPadding=12 * mm, bottomPadding=12 * mm)
    doc.addPageTemplates([PageTemplate(id="sb", frames=[full_frame], onPage=_draw_sidebar_bg)])

    styles = getSampleStyleSheet()

    # Sidebar styles (white on teal)
    s_sname = ParagraphStyle("SBName", parent=styles["Title"], fontSize=18, textColor=SIDEBAR_WHITE, spaceAfter=1 * mm, alignment=TA_LEFT, fontName="Helvetica-Bold")
    s_stitle = ParagraphStyle("SBTitle", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=SIDEBAR_LIGHT, spaceAfter=3 * mm, leading=_leading(SIZE_BODY))
    s_ssection = ParagraphStyle("SBSect", parent=styles["Heading3"], fontSize=10, textColor=SIDEBAR_WHITE, spaceBefore=4 * mm, spaceAfter=1.5 * mm, fontName="Helvetica-Bold")
    s_slabel = ParagraphStyle("SBLabel", parent=styles["Normal"], fontSize=SIZE_SMALL, textColor=SIDEBAR_DIM, leading=_leading(SIZE_SMALL))
    s_svalue = ParagraphStyle("SBVal", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=SIDEBAR_WHITE, leading=_leading(SIZE_SUB))
    s_sbody = ParagraphStyle("SBBody", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=SIDEBAR_LIGHT, leading=_leading(SIZE_SUB))

    # Main styles (dark on cream)
    s_msection = ParagraphStyle("SBMSect", parent=styles["Heading2"], fontSize=13, textColor=SIDEBAR_TEAL, spaceBefore=SPACE_SECTION_BEFORE, spaceAfter=SPACE_SECTION_AFTER, fontName="Helvetica-Bold", keepWithNext=1)
    s_mentry = ParagraphStyle("SBMEntry", parent=styles["Normal"], fontSize=SIZE_BODY, textColor=SIDEBAR_DARK, leading=_leading(SIZE_BODY))
    s_msub = ParagraphStyle("SBMSub", parent=styles["Normal"], fontSize=SIZE_SUB, textColor=HexColor("#888888"), leading=_leading(SIZE_SUB))
    s_mbullet = ParagraphStyle("SBMBull", parent=styles["Normal"], fontSize=9.5, textColor=SIDEBAR_DARK, leading=_leading(9.5), leftIndent=12, bulletIndent=2)

    pi = data.get("personal_info", {})
    skills = data.get("skills", {})

    # ── Sidebar content ──
    side = []
    side.append(Paragraph(pi.get("name", ""), s_sname))
    obj = data.get("objective", "")
    if obj:
        short = obj[:100].rsplit(" ", 1)[0] + "..." if len(obj) > 100 else obj
        side.append(Paragraph(short, s_stitle))

    # Profile photo
    if profile_image_url:
        img_buf = _fetch_image_bytes(profile_image_url)
        if img_buf:
            side.append(Spacer(1, 3 * mm))
            side.append(CircularImage(img_buf, size=50 * mm))
            side.append(Spacer(1, 3 * mm))

    # Personal info
    side.append(Paragraph("PERSONAL INFO", s_ssection))
    for label, key in [("Email", "email"), ("Phone", "phone"), ("Location", "location")]:
        val = pi.get(key)
        if val:
            side.append(Paragraph(label.upper(), s_slabel))
            side.append(Paragraph(val, s_svalue))
            side.append(Spacer(1, 1.5 * mm))

    # Links
    links = [(k, pi.get(k)) for k in ["linkedin", "portfolio"] if pi.get(k)]
    if links:
        side.append(Paragraph("LINKS", s_ssection))
        for label, val in links:
            side.append(Paragraph(label.upper(), s_slabel))
            side.append(Paragraph(val, s_svalue))
            side.append(Spacer(1, 1.5 * mm))

    # Skills
    if any(skills.get(k) for k in ["technical", "tools", "soft"]):
        side.append(Paragraph("SKILLS", s_ssection))
        for cat, key in [("Technical", "technical"), ("Tools", "tools"), ("Soft Skills", "soft")]:
            if skills.get(key):
                side.append(Paragraph(cat.upper(), s_slabel))
                side.append(Paragraph(", ".join(skills[key]), s_sbody))
                side.append(Spacer(1, 2 * mm))

    # Languages
    if skills.get("languages"):
        side.append(Paragraph("LANGUAGES", s_ssection))
        side.append(Paragraph(", ".join(skills["languages"]), s_sbody))

    # Certifications
    certs = data.get("certifications", [])
    if certs:
        side.append(Paragraph("CERTIFICATIONS", s_ssection))
        for c in certs:
            side.append(Paragraph(f"{BULLET_CHAR} {c.get('name', '')} ({c.get('year', '')})", s_sbody))

    # ── Main content ──
    main = []

    # Experience
    exp_list = data.get("experience", [])
    if exp_list:
        main.append(Paragraph("WORK EXPERIENCE", s_msection))
        for exp in exp_list:
            main.append(Paragraph(f"<b>{exp.get('title', '')}</b> -- {exp.get('company', '')}", s_mentry))
            if exp.get("duration"):
                main.append(Paragraph(exp["duration"], s_msub))
            for b in exp.get("bullets", []):
                main.append(Paragraph(b, s_mbullet, bulletText=BULLET_CHAR))
            main.append(Spacer(1, SPACE_ENTRY_GAP))

    # Education
    edu_list = data.get("education", [])
    if edu_list:
        main.append(Paragraph("EDUCATION", s_msection))
        for e in edu_list:
            main.append(Paragraph(f"<b>{e.get('degree', '')}</b> -- {e.get('institution', '')}", s_mentry))
            sub = [p for p in [e.get("year"), e.get("grade")] if p]
            if sub:
                main.append(Paragraph(" | ".join(sub), s_msub))
            main.append(Spacer(1, SPACE_ENTRY_GAP))

    # Projects
    proj_list = data.get("projects", [])
    if proj_list:
        main.append(Paragraph("PROJECTS", s_msection))
        for p in proj_list:
            tech = f" ({', '.join(p.get('tech_stack', []))})" if p.get("tech_stack") else ""
            main.append(Paragraph(f"<b>{p.get('name', '')}</b>{tech}", s_mentry))
            for b in p.get("bullets", []):
                main.append(Paragraph(b, s_mbullet, bulletText=BULLET_CHAR))
            main.append(Spacer(1, SPACE_ENTRY_GAP))

    # Achievements
    achievements = data.get("achievements", [])
    if achievements:
        main.append(Paragraph("ACHIEVEMENTS", s_msection))
        for a in achievements:
            main.append(Paragraph(a, s_mbullet, bulletText=BULLET_CHAR))

    # ── Two-column table ──
    side_w = sw - 2 * mm
    main_w = mw - 2 * mm
    side_cell = side if side else [Spacer(1, 1)]
    main_cell = main if main else [Spacer(1, 1)]

    t = Table([[side_cell, main_cell]], colWidths=[side_w, main_w])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (0, 0), 12 * mm),
        ("RIGHTPADDING", (0, 0), (0, 0), 8 * mm),
        ("LEFTPADDING", (1, 0), (1, 0), 8 * mm),
        ("RIGHTPADDING", (1, 0), (1, 0), 12 * mm),
    ]))

    doc.build([t])
    buffer.seek(0)
    return buffer.read()


# ─── Template 6: Jake (ATS Classic, Black & White) ─────────

JAKE_BLACK = HexColor("#000000")
JAKE_DARK = HexColor("#1A1A1A")
JAKE_GRAY = HexColor("#555555")


def _generate_jake(data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=MARGIN_TIGHT, bottomMargin=MARGIN_TIGHT,
        leftMargin=MARGIN_TIGHT, rightMargin=MARGIN_TIGHT,
    )
    styles = getSampleStyleSheet()
    page_w = A4[0] - 2 * MARGIN_TIGHT

    s_name = ParagraphStyle(
        "JKName", parent=styles["Title"], fontSize=22,
        textColor=JAKE_BLACK, spaceAfter=1 * mm,
        alignment=TA_CENTER, fontName="Helvetica-Bold",
    )
    s_contact = ParagraphStyle(
        "JKContact", parent=styles["Normal"], fontSize=SIZE_CONTACT,
        textColor=JAKE_DARK, spaceAfter=4 * mm,
        alignment=TA_CENTER, leading=_leading(SIZE_CONTACT, 1.3),
    )
    s_section = ParagraphStyle(
        "JKSection", parent=styles["Heading2"], fontSize=SIZE_SECTION,
        textColor=JAKE_BLACK, spaceBefore=4 * mm, spaceAfter=0.5 * mm,
        fontName="Helvetica-Bold", keepWithNext=1,
    )
    s_entry_bold = ParagraphStyle(
        "JKEntryBold", parent=styles["Normal"], fontSize=SIZE_ENTRY_TITLE,
        textColor=JAKE_BLACK, leading=_leading(SIZE_ENTRY_TITLE, 1.3), fontName="Helvetica-Bold",
    )
    s_entry_right = ParagraphStyle(
        "JKEntryRight", parent=styles["Normal"], fontSize=SIZE_ENTRY_TITLE,
        textColor=JAKE_BLACK, leading=_leading(SIZE_ENTRY_TITLE, 1.3), fontName="Helvetica-Bold",
        alignment=TA_RIGHT,
    )
    s_entry_italic = ParagraphStyle(
        "JKEntryItalic", parent=styles["Normal"], fontSize=SIZE_SUB,
        textColor=JAKE_GRAY, leading=_leading(SIZE_SUB, 1.3), fontName="Helvetica-Oblique",
    )
    s_entry_italic_r = ParagraphStyle(
        "JKEntryItalicR", parent=styles["Normal"], fontSize=SIZE_SUB,
        textColor=JAKE_GRAY, leading=_leading(SIZE_SUB, 1.3), fontName="Helvetica-Oblique",
        alignment=TA_RIGHT,
    )
    s_bullet = ParagraphStyle(
        "JKBullet", parent=styles["Normal"], fontSize=SIZE_BODY,
        textColor=JAKE_DARK, leading=_leading(SIZE_BODY, 1.3),
        leftIndent=14, bulletIndent=4,
    )
    s_body = ParagraphStyle(
        "JKBody", parent=styles["Normal"], fontSize=SIZE_BODY,
        textColor=JAKE_DARK, leading=_leading(SIZE_BODY, 1.3),
    )

    entry_style = TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
    ])

    GRAY_BG = HexColor("#F0F0F0")

    def add_section(title):
        s_hdr = ParagraphStyle("JHdr", parent=styles["Normal"], fontSize=SIZE_SECTION, textColor=JAKE_BLACK, fontName="Helvetica-Bold", leading=_leading(SIZE_SECTION, 1.2))
        t = Table([[Paragraph(title, s_hdr)]], colWidths=[page_w])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), GRAY_BG),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 2.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
        ]))
        elements.append(Spacer(1, SPACE_SECTION_BEFORE))
        elements.append(t)
        elements.append(Spacer(1, SPACE_SECTION_AFTER))

    elements = []
    pi = data.get("personal_info", {})

    # ── Name (large, centered, uppercase for small-caps effect)
    name = pi.get("name", "")
    elements.append(Paragraph(name.upper(), s_name))

    # ── Contact line (plain text, no unicode icons — Helvetica safe)
    contact_parts = []
    if pi.get("phone"):
        contact_parts.append(pi["phone"])
    if pi.get("email"):
        contact_parts.append(pi["email"])
    if pi.get("linkedin"):
        contact_parts.append(pi["linkedin"])
    if pi.get("github") or pi.get("portfolio"):
        contact_parts.append(pi.get("github") or pi.get("portfolio"))
    if contact_parts:
        elements.append(Paragraph(CONTACT_SEP.join(contact_parts), s_contact))

    # ── Objective / Summary
    obj = data.get("objective", "")
    if obj:
        add_section("Summary")
        elements.append(Paragraph(obj, s_body))

    # ── Education
    edu_list = data.get("education", [])
    if edu_list:
        add_section("Education")
        s_edu_hdr = ParagraphStyle(
            "JKEduHdr", parent=styles["Normal"], fontSize=SIZE_BODY,
            textColor=WHITE, fontName="Helvetica-Bold", leading=_leading(SIZE_BODY, 1.3),
        )
        s_edu_cell = ParagraphStyle(
            "JKEduCell", parent=styles["Normal"], fontSize=SIZE_BODY,
            textColor=JAKE_DARK, leading=_leading(SIZE_BODY, 1.3),
        )
        edu_header = [
            Paragraph("<b>Year</b>", s_edu_hdr),
            Paragraph("<b>Degree / Certificate</b>", s_edu_hdr),
            Paragraph("<b>Institute</b>", s_edu_hdr),
            Paragraph("<b>CGPA / %</b>", s_edu_hdr),
        ]
        edu_rows = [edu_header]
        for e in edu_list:
            degree = e.get("degree", "")
            if e.get("stream"):
                degree += f", {e['stream']}"
            edu_rows.append([
                Paragraph(e.get("year", ""), s_edu_cell),
                Paragraph(degree, s_edu_cell),
                Paragraph(e.get("institution", ""), s_edu_cell),
                Paragraph(e.get("grade", ""), s_edu_cell),
            ])
        edu_col_widths = [page_w * 0.15, page_w * 0.35, page_w * 0.35, page_w * 0.15]
        edu_table = Table(edu_rows, colWidths=edu_col_widths)
        edu_ts = [
            ("BACKGROUND", (0, 0), (-1, 0), JAKE_BLACK),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, GRAY_400),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]
        for i in range(1, len(edu_rows)):
            bg = GRAY_BG if i % 2 == 0 else WHITE
            edu_ts.append(("BACKGROUND", (0, i), (-1, i), bg))
        edu_table.setStyle(TableStyle(edu_ts))
        elements.append(edu_table)

    # ── Experience
    exp_list = data.get("experience", [])
    if exp_list:
        add_section("Experience")
        for exp in exp_list:
            entry = []
            row1 = Table(
                [[Paragraph(f"<b>{exp.get('company', '')}</b>", s_entry_bold),
                  Paragraph(f"<b>{exp.get('duration', '')}</b>", s_entry_right)]],
                colWidths=[page_w * 0.65, page_w * 0.35],
            )
            row1.setStyle(entry_style)
            entry.append(row1)
            location = exp.get("location", "")
            row2 = Table(
                [[Paragraph(exp.get("title", ""), s_entry_italic),
                  Paragraph(location, s_entry_italic_r)]],
                colWidths=[page_w * 0.65, page_w * 0.35],
            )
            row2.setStyle(entry_style)
            entry.append(row2)
            for b in exp.get("bullets", []):
                entry.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # ── Projects
    proj_list = data.get("projects", [])
    if proj_list:
        add_section("Projects")
        for p in proj_list:
            entry = []
            ts = p.get("tech_stack", [])
            title_left = f"<b>{p.get('name', '')}</b>"
            if ts:
                title_left += f"  |  <i>{', '.join(ts)}</i>"
            row1 = Table(
                [[Paragraph(title_left, s_entry_bold),
                  Paragraph("", s_entry_right)]],
                colWidths=[page_w * 0.75, page_w * 0.25],
            )
            row1.setStyle(entry_style)
            entry.append(row1)
            for b in p.get("bullets", []):
                entry.append(Paragraph(b, s_bullet, bulletText=BULLET_CHAR))
            entry.append(Spacer(1, SPACE_ENTRY_GAP))
            elements.append(KeepTogether(entry))

    # ── Achievements
    achievements = data.get("achievements", [])
    if achievements:
        add_section("Achievements")
        for a in achievements:
            elements.append(Paragraph(a, s_bullet, bulletText=BULLET_CHAR))

    # ── Skills
    skills = data.get("skills", {})
    if any(skills.get(k) for k in ["technical", "soft", "languages", "tools"]):
        add_section("Technical Skills")
        for label, key in [("Languages", "languages"), ("Technologies/Frameworks", "technical"), ("Developer Tools", "tools"), ("Soft Skills", "soft")]:
            if skills.get(key):
                elements.append(Paragraph(f"<b>{label}:</b> {', '.join(skills[key])}", s_body))
                elements.append(Spacer(1, 1 * mm))

    # ── Certifications
    certs = data.get("certifications", [])
    if certs:
        add_section("Certifications")
        for c in certs:
            line = f"<b>{c.get('name', '')}</b>"
            parts = [p for p in [c.get("issuer"), c.get("year")] if p]
            if parts:
                line += f" -- {', '.join(parts)}"
            elements.append(Paragraph(line, s_body))

    doc.build(elements, onFirstPage=_draw_page_footer, onLaterPages=_draw_page_footer)
    buffer.seek(0)
    return buffer.read()
