import os


TURSO_DATABASE_URL = os.environ["TURSO_DATABASE_URL"]
TURSO_AUTH_TOKEN = os.environ["TURSO_AUTH_TOKEN"]
JWT_SECRET = os.environ["JWT_SECRET"]
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_DAYS = 7

SQLALCHEMY_DATABASE_URL = (
    f"{TURSO_DATABASE_URL}?authToken={TURSO_AUTH_TOKEN}"
)
