import os


TURSO_DATABASE_URL = os.environ["TURSO_DATABASE_URL"]
TURSO_AUTH_TOKEN = os.environ["TURSO_AUTH_TOKEN"]
JWT_SECRET = os.environ["JWT_SECRET"]
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_DAYS = 7

ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]

# Turso docs: sqlite+{TURSO_DATABASE_URL}?secure=true
SQLALCHEMY_DATABASE_URL = f"sqlite+{TURSO_DATABASE_URL}?secure=true"
