import React from 'react'
import {
  AbsoluteFill,
  Audio,
  Sequence,
  staticFile,
  useVideoConfig,
} from 'remotion'
import type { CourseScript } from '../scripts/course-scripts'
import { WhiteboardScene } from '../components/WhiteboardScene'
import { TitleCard } from '../components/TitleCard'
import { SubtitleBar } from '../components/SubtitleBar'
import { SceneDivider } from '../components/SceneDivider'
import { QuizTransition } from '../components/QuizTransition'

const SEGMENT_DURATION_SEC = 150
const TITLE_CARD_DURATION_SEC = 3
const DIVIDER_DURATION_SEC = 1
const QUIZ_TRANSITION_SEC = 2

export interface ModuleVideoProps {
  script: CourseScript
}

export const ModuleVideo: React.FC<ModuleVideoProps> = ({ script }) => {
  const { fps } = useVideoConfig()

  const titleCardFrames = Math.ceil(TITLE_CARD_DURATION_SEC * fps)
  const segmentFrames = Math.ceil(SEGMENT_DURATION_SEC * fps)
  const dividerFrames = Math.ceil(DIVIDER_DURATION_SEC * fps)
  const quizFrames = Math.ceil(QUIZ_TRANSITION_SEC * fps)

  // Content frames = segment - title card - divider - quiz transition (for segments 0-2)
  const contentFramesWithQuiz = segmentFrames - titleCardFrames - dividerFrames - quizFrames
  const contentFramesLast = segmentFrames - titleCardFrames - dividerFrames

  let runningFrame = 0

  return (
    <AbsoluteFill style={{ backgroundColor: '#FAFAFA' }}>
      {script.segments.map((segment, index) => {
        const startFrame = runningFrame
        const isLastSegment = index === script.segments.length - 1
        const contentDuration = isLastSegment ? contentFramesLast : contentFramesWithQuiz

        // Audio file path (generated by elevenlabs.ts)
        const audioFile = `audio/${script.id}-segment-${index}.mp3`

        const element = (
          <React.Fragment key={index}>
            {/* Title card for this segment */}
            <Sequence from={startFrame} durationInFrames={titleCardFrames}>
              <TitleCard
                title={segment.title}
                subtitle={`${script.title} — Segment ${index + 1} of ${script.segments.length}`}
                moduleNumber={index + 1}
              />
            </Sequence>

            {/* Main whiteboard content */}
            <Sequence
              from={startFrame + titleCardFrames}
              durationInFrames={contentDuration}
            >
              <WhiteboardScene
                title={segment.title}
                keyPoints={segment.keyPoints}
                segmentIndex={index}
              />
              {/* Subtitle bar showing narration */}
              <SubtitleBar
                text={segment.narration}
                startFrame={0}
                durationFrames={contentDuration}
              />
            </Sequence>

            {/* Quiz transition (not on last segment) */}
            {!isLastSegment && (
              <Sequence
                from={startFrame + titleCardFrames + contentDuration}
                durationInFrames={quizFrames}
              >
                <QuizTransition />
              </Sequence>
            )}

            {/* Scene divider transition */}
            <Sequence
              from={startFrame + segmentFrames - dividerFrames}
              durationInFrames={dividerFrames}
            >
              <SceneDivider direction={index % 2 === 0 ? 'left' : 'right'} />
            </Sequence>

            {/* Voiceover audio for the full segment */}
            <Sequence from={startFrame + titleCardFrames} durationInFrames={contentDuration}>
              <Audio src={staticFile(audioFile)} volume={1} />
            </Sequence>
          </React.Fragment>
        )

        runningFrame += segmentFrames
        return element
      })}
    </AbsoluteFill>
  )
}
